### ISSUE TITLE
prombackup behind reverse proxy?

### ISSUE THREAD

**Issue by thediveo** [hansmi/prombackup#62]
First: great project I'm glad I found, because it allows to bundle some observability sensors/exporters with Prometheus and your prombackup into a Docker composer deployment that can be used by devs as a low entry barrier into measuring things and giving me their data for analysis.

Now, I would like to set up the deployment to only use a single host port served by a Traefik reverse proxy, and then putting Prometheus and Prombackup behind different HTTP routes. I tried out the following (dynamic) configuration:

```yaml
http:
  routers:
    prombackup:
      rule: 'PathPrefix("/backup/") || Path("/backup")'
      service: prombackup
      middlewares:
        - prombackup-service

  middlewares:
    prombackup-service:
      stripPrefix:
        prefixes:
          - '/backup'
```

While this shows the prombackup's home page, the metrics link fails, as it is root-absolute `/metrics`. The other links seem to be properly relative to the page's location, such as `./api/snapshot`. At the moment I work around the metrics link issue as follows:

```yaml
# static configuration
experimental:
  plugins:
    rewrite-body:
      moduleName: 'github.com/packruler/rewrite-body'
      version: 'v1.2.0'
```

```yaml
# dynamic configuration
http:
  routers:
    prombackup:
      rule: 'PathPrefix("/backup/") || Path("/backup")'
      service: prombackup
      middlewares:
        - prombackup-service
        - prombackup-rewrite-body

  middlewares:
    prombackup-service:
      stripPrefix:
        prefixes:
          - '/backup'
    prombackup-rewrite-body:
      plugin:
        rewrite-body:
          logLevel: 0
          lastModified: true
          monitor:
            methods:
              - GET
          rewrites:
            - regex: '"/metrics"'
              replacement: '"/backup/metrics"'

```

Would it be possible to update the link and release?

In any case: many thanks again!

**Comment by thediveo** [comment]
Noticed that using `/backup` instead of `/backup/` also causes hiccups, that can be fixed with:

```yaml
# ...
    prombackup:
      rule: 'PathPrefix("/backup/") || Path("/backup")'
      service: prombackup
      middlewares:
        - prombackup-redirect
        - prombackup-service
        - prombackup-rewrite-body
# ...
    prombackup-redirect:
      redirectRegex:
        regex: '^http://([^/]+)/backup$'
        replacement: 'http://${1}/backup/'
```
